config/routes.rb
Rails.application.routes.draw do
  devise_for :candidates
  resources :profiles, only: %i[index show new create]
  devise_for :headhunters
  root 'home#index'
  resources :applies, only: %i[show new create]
  resources :job_opportunities, only: %i[show new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/apply.rb
class Apply < ApplicationRecord
  belongs_to :job_opportunity
  belongs_to :candidate
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
  has_many :applies
end

app/models/headhunter.rb
class Headhunter < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/job_opportunity.rb
class JobOpportunity < ApplicationRecord
  EXPERIENCES = ["Estagiário", "Júnior", "Pleno", "Sênior", "Especialista",
    "Diretor"]

  validates :title, :location, :description, :qualifications, :salary_range, 
    :experience_level, :deadline, presence: true

  has_many :applies
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :candidate
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/applies_controller.rb
class AppliesController < ApplicationController
  def new
    @apply = Apply.new
    @jobopp = JobOpportunity.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @jobapp = JobOpportunity.all

    #if candidate_signed_in?
    #  if Profile.find_by(candidate: current_candidate).nil?
    #    redirect_to new_profile_path
    #    flash[:notice] = 'Preencha seu perfil antes de se candidatar'
    #  end
    #end
    
  end
end

app/controllers/job_opportunities_controller.rb
class JobOpportunitiesController < ApplicationController
  before_action :authenticate_headhunter!, only: [:new, :create]

  def show
    @jobopp = JobOpportunity.find(params[:id])
  end

  def new
    @jobopp = JobOpportunity.new
  end

  def create
    @jobopp = JobOpportunity.new(job_params)
    @jobopp.active = true
    if @jobopp.save
      redirect_to @jobopp
    else
      render :new
    end
    
  end

  private

  def job_params
    params.require(:job_opportunity).permit(:title, :description, 
      :qualifications, :salary_range, :experience_level, :deadline, :location, 
      :active)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    if candidate_signed_in?
      @profile = Profile.find_by(candidate: current_candidate)
    end
  end

  def new
    if candidate_signed_in?
      @profile = Profile.new(candidate: current_candidate)
    end
  end

  def create
    if candidate_signed_in?
      @profile = Profile.new(profile_params)
      @profile.save

      redirect_to root_path
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:name, :social_name, :document,
      :birthdate, :formation, :description, :experience, :candidate)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/applies/new.html.erb
<h1>Aplicar para a vaga</h1>

<%= form_with model: @aplly, local: true do |app| %>
  <%= app.label :why_apply %>
  <%= app.text_field :why_apply %>
<% end %>

app/views/home/index.html.erb
<h1>Bem vindo ao sistema de vagas de emprego</h1>

<% if headhunter_signed_in? %>
  <h3><%= link_to 'Cadastrar vagas', new_job_opportunity_path%></h3>
<% end %> 

<% if candidate_signed_in? %>
  <h3><%= link_to 'Perfil', profiles_path %></h3>
<% end %>

<%= link_to 'Entrar', new_headhunter_session_path %>

<% if @jobapp.empty? %>
  Nenhuma vaga criada
<% end %>

<% @jobapp.each do |job| %>
  <h2><%= link_to job.title, job_opportunity_path(id: job.id) %></h2>
  <p><%= l job.deadline %></p>
  <p><%= job.location %></p>
<% end %>

app/views/job_opportunities/new.html.erb
<h1>Nova vaga</h1>

<% @jobopp.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>

<%= form_with model: @jobopp, local: true do |job| %>
  <%= job.label :title %>
  <%= job.text_field :title %>
  <%= job.label :location %>
  <%= job.text_field :location %>
  <%= job.label :description %>
  <%= job.text_field :description %>
  <%= job.label :qualifications %>
  <%= job.text_field :qualifications %>
  <%= job.label :salary_range %>
  <%= job.number_field :salary_range %>
  <%= job.label :experience_level %>
  <%= job.select(:experience_level, JobOpportunity::EXPERIENCES) %>
  <%= job.label :deadline %>
  <%= job.date_field :deadline %>
  <%= job.submit 'Cadastrar vaga' %>
<% end %>

app/views/job_opportunities/show.html.erb
<h1><%= @jobopp.title %></h1>
<h3> <%= JobOpportunity.human_attribute_name(:location) %>: 
  <%= @jobopp.location %> </h3>
<h3> <%= JobOpportunity.human_attribute_name(:deadline) %>:
  <%= l @jobopp.deadline %> </h3>
<p> <%= JobOpportunity.human_attribute_name(:description) %>:
  <%= @jobopp.description %></p>
<p> <%= JobOpportunity.human_attribute_name(:qualifications) %>:
  <%= @jobopp.qualifications %></p>
<p> <%= JobOpportunity.human_attribute_name(:salary_range) %>:
  <%= number_to_currency(@jobopp.salary_range) %></p>
<p> <%= JobOpportunity.human_attribute_name(:experience_level) %>:
  <%= @jobopp.experience_level %></p>

<% if candidate_signed_in? %>
  <%= link_to 'Candidatar-se', new_apply_path(id: @jobopp)%>
<% else %>
  <%= link_to 'Candidatar-se', new_candidate_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:notice] %>
    <%= flash[:alert] %>
    <%= yield %>
  </body>
</html>

app/views/profiles/index.html.erb
<% if not @profile.nil? %>

  <h1><%= Profile.human_attribute_name(:name) %>: <%= @profile.name %></h1>

  <h2><%= Profile.human_attribute_name(:social_name) %>: 
    <%= @profile.social_name %></h2>

  <p><%= Profile.human_attribute_name(:document) %>: <%= @profile.document %></p>

  <p><%= Profile.human_attribute_name(:birthday) %>: 
    <%= l @profile.birthday %></p>

  <p><%= Profile.human_attribute_name(:formation) %>: 
    <%= @profile.formation %></p>

  <p><%= Profile.human_attribute_name(:description) %>: 
    <%= @profile.description %></p>
    
  <p><%= Profile.human_attribute_name(:experience) %>: 
    <%= @profile.experience %></p>

  <p><%= Candidate.human_attribute_name(:email) %>: 
    <%= @profile.candidate.email %></p>
<% end %>

<%= link_to 'Criar perfil', new_profile_path %>
<%= link_to 'Ver vagas', root_path %>

app/views/profiles/new.html.erb
<h1>Edite seu perfil</h1>

<%= form_with model: @profile, local: true do |pro|%>
  <%= pro.label :name%>
  <%= pro.text_field :name%>
  <%= pro.label :social_name%>
  <%= pro.text_field :social_name%>
  <%= pro.label :document%>
  <%= pro.text_field :document%>
  <%= pro.label :birthday%>
  <%= pro.date_field :birthday%>
  <%= pro.label :formation%>
  <%= pro.text_field :formation%>
  <%= pro.label :description%>
  <%= pro.text_field :description%>
  <%= pro.label :experience%>
  <%= pro.text_field :experience%>
  <%= pro.submit 'Salvar'%>
<% end %>